server:
  port: 2001

spring:
  application:
    name: TaskManagement-task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_task
    username: postgres
    password: Kuna@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:2003/eureka/
