server:
  port: 2000

spring:
  application:
    name: TaskManagement-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: postgres
    password: Kuna@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

